export 'splachscreen.dart';
export 'sin_in_screen.dart';
export 'class_for_text.dart';
export 'class_for_textfields.dart';
export 'class_for_bottons.dart';
export 'retailer_create_account.dart';
export 'forget_password.dart';
export 'reset_password.dart';
export 'login_again.dart';